version: '2'
services:
mage:
    image: goesta/xmage-alpine
    ports:
     - "17171:17171"
     - "17179:17179"
    extra_hosts:
     - "bobdebouwer.net:0.0.0.0"
    environment:
     - XMAGE_DOCKER_SERVER_ADDRESS=bobdebouwer.net
     - XMAGE_DOCKER_SERVER_NAME=bobzijnserver
     - XMAGE_DOCKER_MAX_SECONDS_IDLE=6000
     - XMAGE_DOCKER_AUTHENTICATION_ACTIVATED=false
    volumes:
     - xmage-db:/xmage/mage-server/db
     - xmage-saved:/xmage/mage-server/saved
volumes:
    xmage-db:
        driver: local
    xmage-saved:
        driver: local